export const LOGIN = 'LOGIN';
export const LOGIN_IS_LOADING = 'LOGIN_IS_LOADING';
export const LOGIN_ERROR = 'LOGIN_ERROR';
export const SAVE_USER_INFO = 'SAVE_USER_INFO';
export const FETCH_PRODUCTS = 'FETCH_PRODUCTS';
export const ADD_TO_CART = 'ADD_TO_CART';
export const EMPTY_CART = 'EMPTY_CART';
export const REMOVE_FROM_CART = 'REMOVE_FROM_CART';
export const ADD_ORDER = 'ADD_ORDER';
export const UPDATE_CARD_ITEM_COUNT = 'UPDATE_CARD_ITEM_COUNT';
export const FETCH_FROM_CART = 'FETCH_FROM_CART';

export const LOGIN_REQUEST = 'USERS_LOGIN_REQUEST';
export const LOGIN_SUCCESS = 'USERS_LOGIN_SUCCESS';
export const LOGIN_FAILURE = 'USERS_LOGIN_FAILURE';
export const LOGOUT = 'USERS_LOGOUT';

export const userConstants = {
    REGISTER_REQUEST: 'USERS_REGISTER_REQUEST',
    REGISTER_SUCCESS: 'USERS_REGISTER_SUCCESS',
    REGISTER_FAILURE: 'USERS_REGISTER_FAILURE',
    VERIFY_OTP_REQUEST: 'VERIFY_OTP_REQUEST',
    VERIFY_OTP_SUCCESS: 'VERIFY_OTP_SUCCESS',
    VERIFY_OTP_FAILURE: 'VERIFY_OTP_FAILURE',
    UPDATE_USER_REQUEST: 'UPDATE_USER_REQUEST',
    UPDATE_USER_SUCCESS: 'UPDATE_USER_SUCCESS',
    UPDATE_USER_FAILURE: 'UPDATE_USER_FAILURE',
    LOGIN_REQUEST: 'LOGIN_REQUEST',
    LOGIN_SUCCESS: 'LOGIN_SUCCESS',
    TOKEN_RESTORE: 'TOKEN_RESTORE',
    LOGIN_FAILURE: 'LOGIN_FAILURE',
    LOGOUT_REQUEST: 'LOGOUT_REQUEST',
    ADDRESS_REQUEST: 'ADDRESS_REQUEST',
    ADDRESS_SUCCESS: 'ADDRESS_SUCCESS',
    ADDRESS_FAILURE: 'ADDRESS_FAILURE',
    ADDRESS_FETCH:'ADDRESS_FETCH',
    ORDER_SUCCESS: 'ORDER_SUCCESS',
    ORDER_REQUEST: 'ORDER_REQUEST',
    ORDER_FAILURE: 'ORDER_FAILURE',
    ORdER_FETCH:'ORdER_FETCH'
}

export const alertConstants = {
    SUCCESS: 'ALERT_SUCCESS',
    ERROR: 'ALERT_ERROR',
    CLEAR: 'ALERT_CLEAR'
};


